apiVersion: v1
kind: Namespace
metadata:
  name: project-part3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
  namespace: project-part3
spec:
  replicas: 2  # Number of pods
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: projectpart.azurecr.io/project_part3-book_catalog:latest  # Your ACR image URL
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://project_part3_zhbp_user:ZRP6vvc3l22pjSrUUWXTgxwpTW6BrAAg@dpg-crfn9plsvqrc73abeku0-a.oregon-postgres.render.com/project_part3_zhbp?sslmode=require"

---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
  namespace: project-part3
spec:
  selector:
    app: book-catalog
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 8000
  type: LoadBalancer  # Exposes the service externally

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
  namespace: project-part3
spec:
  replicas: 2  # Number of pods
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management
        image: projectpart.azurecr.io/project_part3-inventory_management:latest  # Your ACR image URL
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://project_part3_zhbp_user:ZRP6vvc3l22pjSrUUWXTgxwpTW6BrAAg@dpg-crfn9plsvqrc73abeku0-a.oregon-postgres.render.com/project_part3_zhbp?sslmode=require"

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
  namespace: project-part3
spec:
  selector:
    app: inventory-management
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 8000
  type: LoadBalancer  # Exposes the service externally
